# Generated by Selenium IDE - Optimized for Wipro NGA Labs
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class TestQ2():
    def setup_method(self, method):
        # Using Chrome as per your environment
        self.driver = webdriver.Chrome()
        # Adding an implicit wait as a safety net
        self.driver.implicitly_wait(5)

    def teardown_method(self, method):
        self.driver.quit()

    def test_q2_login(self):
        # 1. Navigate to the login page
        self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        self.driver.set_window_size(1169, 824)

        # Initialize Explicit Wait
        wait = WebDriverWait(self.driver, 10)

        # 2. Wait for and enter Username
        user_input = wait.until(EC.visibility_of_element_located((By.NAME, "username")))
        user_input.send_keys("Admin")

        # 3. Enter Password
        pass_input = wait.until(EC.visibility_of_element_located((By.NAME, "password")))
        pass_input.send_keys("admin123")

        # 4. Click Login Button
        self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()

        # 5. Validation: Check if we reached the Dashboard
        dashboard_header = wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".oxd-topbar-header-title")))
        assert "Dashboard" in dashboard_header.text