# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab1(self):
    # Test name: Lab1
    # Step # | name | target | value
    # 1 | open | https://www.google.com/ | 
    self.driver.get("https://www.google.com/")
    # 2 | setWindowSize | 653x680 | 
    self.driver.set_window_size(653, 680)
    # 3 | click | id=APjFqb | 
    self.driver.find_element(By.ID, "APjFqb").click()
    # 4 | type | id=APjFqb | wipro
    self.driver.find_element(By.ID, "APjFqb").send_keys("wipro")
    # 5 | click | css=.ExCKkf > svg | 
    self.driver.find_element(By.CSS_SELECTOR, ".ExCKkf > svg").click()
  
