# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab3(self):
    # Test name: Lab3
    # Step # | name | target | value
    # 1 | open | https://demo.opencart.com/ | 
    self.driver.get("https://demo.opencart.com/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | linkText=Phones & PDAs | 
    self.driver.find_element(By.LINK_TEXT, "Phones & PDAs").click()
    # 4 | click | id=input-sort | 
    self.driver.find_element(By.ID, "input-sort").click()
    # 5 | select | id=input-sort | label=Name (A - Z)
    dropdown = self.driver.find_element(By.ID, "input-sort")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
    # 6 | runScript | window.scrollTo(0,400) | 
    self.driver.execute_script("window.scrollTo(0,400)")
    # 7 | mouseOver | css=.col:nth-child(1) button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) button:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | click | css=.col:nth-child(1) button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) button:nth-child(1)").click()
    # 9 | mouseOut | css=.col:nth-child(1) button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
