# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab4():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab4(self):
    # Test name: Lab4
    # Step # | name | target | value
    # 1 | open | https://demo.opencart.com/ | 
    self.driver.get("https://demo.opencart.com/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | css=.fa-bars | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-bars").click()
    # 4 | click | linkText=Desktops | 
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    # 5 | click | linkText=Mac (1) | 
    self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
    # 6 | click | id=input-sort | 
    self.driver.find_element(By.ID, "input-sort").click()
    # 7 | select | id=input-sort | label=Name (A - Z)
    dropdown = self.driver.find_element(By.ID, "input-sort")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
    # 8 | type | name=search | Monitors
    self.driver.find_element(By.NAME, "search").send_keys("Monitors")
    # 9 | click | css=.btn-lg:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg:nth-child(2)").click()
    # 10 | click | id=input-description | 
    self.driver.find_element(By.ID, "input-description").click()
    # 11 | click | id=button-search | 
    self.driver.find_element(By.ID, "button-search").click()
  
