# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
class TestTc001():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  def test_tc001(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    self.driver.set_window_size(653, 680)

    # Create a wait object (waits up to 10 seconds)
    wait = WebDriverWait(self.driver, 10)

    # Wait for the username field to be present and visible
    username_field = wait.until(EC.visibility_of_element_located((By.NAME, "username")))
    username_field.click()
    username_field.send_keys("Admin")

    # Do the same for the password field
    password_field = wait.until(EC.visibility_of_element_located((By.NAME, "password")))
    password_field.send_keys("admin123")

    # Click the login button
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    dashboard_header = wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".oxd-topbar-header-title")))
    assert "Dashboard" in dashboard_header.text
  
