# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab2(self):
    # Test name: Lab2
    # Step # | name | target | value
    # 1 | open | https://demo.opencart.com/ | 
    self.driver.get("https://demo.opencart.com/")
    # 2 | setWindowSize | 655x682 | 
    self.driver.set_window_size(655, 682)
    # 3 | mouseOver | css=.col:nth-child(1) > .product-thumb button:nth-child(2) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) > .product-thumb button:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | mouseOut | css=.col:nth-child(1) > .product-thumb button:nth-child(2) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 5 | mouseOver | css=.col:nth-child(1) > .product-thumb button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) > .product-thumb button:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | click | css=.col:nth-child(1) > .product-thumb button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) > .product-thumb button:nth-child(1)").click()
    # 7 | mouseOut | css=.col:nth-child(1) > .product-thumb button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 8 | mouseOver | css=.col:nth-child(2) button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(2) button:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | mouseOut | css=.col:nth-child(2) button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 10 | click | css=.col:nth-child(2) .fa-shopping-cart | 
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(2) .fa-shopping-cart").click()
    # 11 | runScript | window.scrollTo(0,800) | 
    self.driver.execute_script("window.scrollTo(0,800)")
    # 12 | mouseOver | css=.col:nth-child(3) button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(3) button:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 13 | click | css=.col:nth-child(3) button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(3) button:nth-child(1)").click()
    # 14 | mouseOut | css=.col:nth-child(3) button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 15 | mouseOut | css=.col:nth-child(3) button:nth-child(2) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 16 | mouseOut | css=.col:nth-child(4) button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 17 | click | xpath=//button[@id='button-cart'] | 
    self.driver.find_element(By.XPATH, "//button[@id=\'button-cart\']").click()
    # 18 | mouseOver | id=button-cart | 
    element = self.driver.find_element(By.ID, "button-cart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 19 | mouseOut | id=button-cart | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 20 | click | css=.breadcrumb-item:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".breadcrumb-item:nth-child(1)").click()
  
